name: "AK9753 Grove Human Presence Sensor"
description: "Support for the Grove Human Presence Sensor (AK9753)"
platform: "i2c"
dependencies:
  - i2c
options:
  - name: "i2c_addr"
    type: "int"
    default: 0x64
examples:
  - "example.yaml"